CREATE TABLE users(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(20) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	email VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	user_type VARCHAR(20) DEFAULT 'user' NOT NULL,
	membership_type VARCHAR(20) NOT NULL,
	created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) AUTO_INCREMENT=100000;

CREATE TABLE support_chat(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id INTEGER NOT NULL,
	status VARCHAR(20) DEFAULT 'open' NOT NULL,
	started_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(ID)
) AUTO_INCREMENT=100000;

CREATE TABLE support_chat_messages(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	chat_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	message VARCHAR(255) NOT NULL,
	sent_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (chat_id) REFERENCES support_chat(ID),
	FOREIGN KEY (user_id) REFERENCES users(ID)
) AUTO_INCREMENT=100000;

CREATE TABLE articles (
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	creator_id INTEGER NOT NULL,
	title VARCHAR(20) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	article_type VARCHAR(20) NOT NULL,
	price INTEGER DEFAULT 0 NOT NULL,
	created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (creator_id) REFERENCES users(ID)
) AUTO_INCREMENT=100000;

CREATE TABLE forum_threads(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	creator_id INTEGER NOT NULL,
	title VARCHAR(20) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	thread_type VARCHAR(20) NOT NULL,
	price INTEGER DEFAULT 0 NOT NULL,
	created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (creator_id) REFERENCES users(ID)
) AUTO_INCREMENT=100000;

CREATE TABLE forum_messages(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	thread_id INTEGER NOT NULL,
	creator_id INTEGER NOT NULL,
	replying_to INTEGER,
	message VARCHAR(255) NOT NULL,
	sent_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (thread_id) REFERENCES forum_threads(ID),
	FOREIGN KEY (creator_id) REFERENCES users(ID),
	FOREIGN KEY (replying_to) REFERENCES forum_messages(ID)
) AUTO_INCREMENT=100000;

CREATE TABLE contact(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(20) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	message VARCHAR(1000) NOT NULL,
	sent_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT=100000;

CREATE TABLE article_purchase_history(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id INTEGER NOT NULL,
	item_id INTEGER NOT NULL,
	purchased_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(ID),
	FOREIGN KEY (item_id) REFERENCES articles(ID)
) AUTO_INCREMENT=100000;

CREATE TABLE forum_purchase_history(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id INTEGER NOT NULL,
	item_id INTEGER NOT NULL,
	purchased_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(ID),
	FOREIGN KEY (item_id) REFERENCES forum_threads(ID)
) AUTO_INCREMENT=100000;

